okta:
  client:
    orgUrl: https://dev-141624.oktapreview.com
    token: XXX
security:
    oauth2:
      client:
        access-token-uri: https://dev-141624.oktapreview.com/oauth2/default/v1/token
        user-authorization-uri: https://dev-141624.oktapreview.com/oauth2/default/v1/authorize
        client-id: 0oag06majtZeZByfQ0h7
        client-secret: r75iY8yOLSOlLUuzvSQGbtOh5_mU8XI6JmcG4wUw
      resource:
        user-info-uri: https://dev-141624.oktapreview.com/oauth2/default/v1/userinfo
spring:
  profiles:
    active: @spring.profiles.active@